# Generated by Django 4.1.7 on 2023-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.CharField(max_length=250)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('dimensiones', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
    ]
