# Generated by Django 4.1.7 on 2023-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
