# Generated by Django 4.1.7 on 2023-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=50)),
                ('germina', models.IntegerField()),
                ('cosecha', models.IntegerField()),
                ('temporada', models.CharField(choices=[('autumn', 'Otoño'), ('winter', 'Invierno'), ('spring', 'Primavera'), ('summer', 'Verano')], max_length=15)),
                ('temperaturaMax', models.IntegerField()),
                ('temperaturaMin', models.IntegerField()),
                ('riego', models.CharField(max_length=50)),
                ('luz', models.CharField(choices=[('poca', 'Poca luz'), ('moderada', 'Luz Moderada'), ('mucha', 'Bastante Luz')], max_length=15)),
                ('profundidadSembrado', models.IntegerField()),
                ('espacioPlantas', models.IntegerField()),
            ],
        ),
    ]
