# Generated by Django 4.1.7 on 2023-05-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos_api', '0002_alter_cultivo_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='luz',
            field=models.CharField(choices=[('Poca luz', 'poca'), ('Luz Moderada', 'moderada'), ('Bastante Luz', 'mucha')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='temporada',
            field=models.CharField(choices=[('Otoño', 'autumn'), ('Invierno', 'winter'), ('Primavera', 'spring'), ('Verano', 'summer'), ('Otoño, Invierno', 'autumn-winter'), ('Primavera, Verano', 'spring-summer'), ('Todas las estaciones', 'all')], max_length=50),
        ),
    ]
