# Generated by Django 4.1.7 on 2023-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos_api', '0003_alter_cultivo_luz_alter_cultivo_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='riego',
            field=models.CharField(choices=[('Mucha o diariamente', 'bastante'), ('Moderada o cada 3 días', 'moderada'), ('poca o cada 5 días', 'poca')], max_length=50),
        ),
    ]
