# Generated by Django 4.2.2 on 2023-06-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0002_customuser_birth_date_customuser_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='garden',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
