# Generated by Django 4.2.1 on 2023-05-20 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crecimiento',
            fields=[
                ('id_crecimiento', models.AutoField(primary_key=True, serialize=False)),
                ('cosecha', models.CharField(blank=True, max_length=200, null=True)),
                ('siembra', models.CharField(blank=True, max_length=200, null=True)),
                ('germinacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cultivo',
            fields=[
                ('id_cultivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('favorito', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('total', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(auto_now_add=True)),
                ('dir_envio', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('costo', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_prod',
            fields=[
                ('id_tipo_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=200)),
                ('provincia', models.CharField(max_length=200)),
                ('localidad', models.CharField(max_length=200)),
                ('telefono', models.BigIntegerField()),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_tipo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.tipo_prod'),
        ),
        migrations.CreateModel(
            name='jardin',
            fields=[
                ('id_jardin', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cultivo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_siembra', models.DateTimeField(auto_now_add=True)),
                ('fecha_germinacion', models.DateTimeField(auto_now_add=True)),
                ('id_crecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.crecimiento')),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cultivo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.usuario'),
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.cultivo'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.provincia'),
        ),
    ]
