# Generated by Django 4.2.1 on 2023-06-01 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0002_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='crecimiento',
            name='espacioPlantas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='luz',
            field=models.CharField(choices=[('Poca luz', 'poca'), ('Luz Moderada', 'moderada'), ('Bastante Luz', 'mucha')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='profundidadSembrado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='riego',
            field=models.CharField(choices=[('Mucha o diariamente', 'bastante'), ('Regular o cada 3 días', 'regular'), ('poca o cada 5 días', 'poca')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='temperaturaMax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='temperaturaMin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crecimiento',
            name='temporada',
            field=models.CharField(choices=[('Otoño', 'autumn'), ('Invierno', 'winter'), ('Primavera', 'spring'), ('Verano', 'summer'), ('Otoño, Invierno', 'autumn-winter'), ('Primavera, Verano', 'spring-summer'), ('Todas las estaciones', 'all')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='imagen',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=1000)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ABM.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
            },
        ),
    ]
